Repository livan23l/deseos2025, pull requests merged in 2024-12, with the labels that each got.

#3 Feat: Archivo index.html
  index.html
Labels: Feature, Cambio menor

#11 6 crear formulario para la generación de cartas
  css/style.css
  formulario.html
  img/icons/destinatario.svg
  img/icons/incognito-1.svg
  img/icons/incognito-2.svg
  img/icons/mensaje.svg
  img/icons/radio-1.svg
  img/icons/radio-2.svg
  img/icons/radio-3.svg
  img/icons/remitente.svg
Labels: Feature

#15 13 plantilla para cuenta regresiva
  carrusel.html
  css/style.css
  img/icons/anterior.svg
  img/icons/siguiente.svg
  img/imagen-1.jpg
  img/imagen-2.jpg
  img/imagen-3.jpg
  img/imagen-4.jpg
  img/imagen-5.png
  javascripts/carrusel.js
Labels: Feature

#20 Feat: Crear archivo nosotros.html con css y normalize.
  css/style.css
  nosotros.html
Labels: Feature

#22 Fix: Errores de integración con el último Merge
  css/style.css
Labels: Error, Cambio menor

#23 Fix: Solución de integración con las clases en la sección "nosotros" …
  css/style.css
  nosotros.html
Labels: Error, Cambio menor

#24 Fix: Corrección general de tamaños en la sección de nosotros
  css/style.css
Labels: Error, Cambio menor

#26 21 funcionalidad del contador
  css/style.css
  cuenta-regresiva.html
  javascripts/cuenta-regresiva.js
Labels: Feature

#25 Creación de cuenta-regresiva.desde.2025.html reutilizando el contador…
  cuenta-regresiva-desde-2025.html
  cuenta-regresiva.html
  img/gifs/Fuegos.png
Labels: Feature

#30 Feat: combinar todo.
  carrusel.html
  css/style.css
  cuenta-regresiva-desde-2025.html
  cuenta-regresiva.html
  cuenta.html
  generador-carta.html
  header.html
  index.html
  nosotros.html
Labels: Feature

#31 Fix: Solución de problemas de integración con el formulario y correci…
  css/style.css
  formulario.html
  generador-carta.html
Labels: Error, Cambio menor

#36 Feat: Ahora cambiará de bloque según si es antes o después de 2025
  css/style.css
  cuenta.html
  javascripts/cuenta-regresiva.js
Labels: Feature

#37 Feat: Agregar animación de carga al ver contador
  css/style.css
  cuenta.html
  img/gifs/cargando.gif
Labels: Feature

#38 Feature: Creación de footer con estilos y creación de colaboradores e…
  authors.md
  css/style.css
  cuenta.html
  generador-carta.html
  index.html
Labels: Feature

#42 Fix: Solución de problema de integración de footer
  formulario.html
Labels: Error, Cambio menor

#43 Solución de integración de footer 2
  css/style.css
  formulario.html
  generador-carta.html
Labels: Error, Cambio menor

#45 44 generar mecanismo de generación de carta
  carta.html
  css/style.css
  cuenta.html
  generador-carta.html
  img/carrusel/imagen-1.webp
  img/carrusel/imagen-2.webp
  img/carrusel/imagen-3.webp
  img/carta.jpg
  img/imagen-1.jpg
  img/imagen-2.jpg
  img/imagen-3.jpg
  img/imagen-4.jpg
  img/imagen-5.png
  index.html
  javascripts/carrusel.js
  javascripts/cuenta-regresiva.js
  javascripts/generar-tarjeta.js
  javascripts/html2canvas.min.js
  mostrar_carta.html
Labels: Error, Feature

#46 Fix: Se redujo la longitud del mensaje para evitar que se superponga …
  css/style.css
  generador-carta.html
Labels: Error, Cambio menor

#47 Chore: Se recorrió la imagen del fuego artificial central de las cart…
  css/style.css
Labels: Cambio menor

#48 FIx: Arreglé cómo se ven los colores en teléfono
  css/style.css
Labels: Error, Cambio menor
